### ISSUE TITLE
Request for Full Release of MiDepth Dataset

### ISSUE THREAD

**Issue by sunpihai-up** [zzt76/midepth#1]
Dear @zzt76 , 

I am writing to inquire if you have any plans to release the full MiDepth dataset. I am eager to follow your work and contribute to the community by developing a robust monocular depth estimation solution under varying lighting conditions. It would be incredibly helpful if you could provide me with access to the complete MiDepth dataset. I believe this would also enhance the impact and reach of your valuable work.

Thank you very much for your consideration.

pihai

**Comment by zzt76** [comment]
Hi Pihai, this project is handed over to https://github.com/ViktorLiang/midepth. Please contact Liang Yuan (yuanliang07@gmail.com) for further updates :)

**Comment by sunpihai-up** [comment]
> Hi Pihai, this project is handed over to https://github.com/ViktorLiang/midepth. Please contact Liang Yuan ([yuanliang07@gmail.com](mailto:yuanliang07@gmail.com)) for further updates :)

thanks for your help !
